#!/bin/sh
PAL=$PATH
for i in `cat /etc/paths`
    do
        PAL="$PAL:$i"
    done
PATH=$PAL
export $PATH
/Users/zonesoft/anaconda3/python.app/Contents/MacOS/python -m robotide.__init__ $* 2> /dev/null &
